### ISSUE TITLE
请问如何运行程序...

### ISSUE THREAD

**Issue by li99yangg** [smokingrain/WeChat#4]
用的MyEclipse，导入项目以后 文字都是乱码，并且加载不到主类 唉

**Comment by smokingrain** [comment]
@li99yangg 项目右键->Properties->Resource选择UTF-8编码，主类/WeChat/src/com/xk/ui/main/QRLoginWindow.java

**Comment by li99yangg** [comment]
太感谢了😊

**Comment by li99yangg** [comment]
还需要请教一下。。。我这个运行以后 把项目切换到jre1.7以后报了很多错，并且扫二维码后就抛异常了  打不开   很难受
获取状态:window.code=201;
获取状态:window.code=201;
获取状态:window.code=201;
获取状态:window.code=200;window.redirect_uri="https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=A3HlT_j7bp3bPRHeqIVD_yM_@qrticket_0&uuid=wbdyMVEtnA==&lang=zh_CN&scan=1519699550";
获取wxsid和wxuin:<error><ret>0</ret><message></message><skey>@crypt_92c9cb7f_6ece16e958be56fd7142268351aa4541</skey><wxsid>crN6tgC5XmRLofD9</wxsid><wxuin>2025805768</wxuin><pass_ticket>BlqqXHNpeLrghSy2dRGY9TJx1luJTAqt1wBLzLTjDUsbnqqskzxF9vUMPPar3flO</pass_ticket><isgrayscale>1</isgrayscale></error>
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.Error: Unresolved compilation problem: 
	The method sort(MyList<T>.SortItem) is undefined for the type List<T>
)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at com.xk.ui.main.QRLoginWindow.open(QRLoginWindow.java:66)
	at com.xk.ui.main.QRLoginWindow.main(QRLoginWindow.java:51)
Caused by: java.lang.Error: Unresolved compilation problem: 
	The method sort(MyList<T>.SortItem) is undefined for the type List<T>

	at com.xk.uiLib.MyList.addItem(MyList.java:440)
	at com.xk.ui.main.MainWindow.createContents(MainWindow.java:155)
	at com.xk.ui.main.MainWindow.open(MainWindow.java:87)
	at com.xk.ui.main.QRLoginWindow$4$3.run(QRLoginWindow.java:227)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 4 more

**Comment by li99yangg** [comment]
不过说真的做的很棒 我还需要学习很久很久才能达到您这样的水平

**Comment by smokingrain** [comment]
@li99yangg 运用了java8的语法，你先把环境弄到java8

**Comment by li99yangg** [comment]
好的
